-- Durable WhatsApp automation queue and delivery log.
-- Run once in the Supabase SQL editor. Server routes use the service-role key;
-- no browser/client policy is intentionally granted.

create table if not exists public.message_log (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  channel text not null default 'whatsapp',
  template text not null,
  event_type text not null,
  transaction_id text,
  transaction_status text,
  mobile text not null,
  user_id text,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'queued'
    check (status in ('queued', 'processing', 'sent', 'failed', 'skipped')),
  detail text,
  provider_message_id text,
  attempt_count integer not null default 0,
  next_attempt_at timestamptz not null default now(),
  locked_until timestamptz,
  last_error text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Upgrade an earlier/basic message_log table without deleting its history.
alter table public.message_log add column if not exists event_key text;
alter table public.message_log add column if not exists channel text default 'whatsapp';
alter table public.message_log add column if not exists template text;
alter table public.message_log add column if not exists event_type text;
alter table public.message_log add column if not exists transaction_id text;
alter table public.message_log add column if not exists transaction_status text;
alter table public.message_log add column if not exists mobile text;
alter table public.message_log add column if not exists user_id text;
alter table public.message_log add column if not exists payload jsonb default '{}'::jsonb;
alter table public.message_log add column if not exists status text default 'queued';
alter table public.message_log add column if not exists detail text;
alter table public.message_log add column if not exists provider_message_id text;
alter table public.message_log add column if not exists attempt_count integer default 0;
alter table public.message_log add column if not exists next_attempt_at timestamptz default now();
alter table public.message_log add column if not exists locked_until timestamptz;
alter table public.message_log add column if not exists last_error text;
alter table public.message_log add column if not exists sent_at timestamptz;
alter table public.message_log add column if not exists created_at timestamptz default now();
alter table public.message_log add column if not exists updated_at timestamptz default now();

update public.message_log
set event_key = 'legacy:' || id::text
where event_key is null;

alter table public.message_log alter column event_key set not null;
create unique index if not exists message_log_event_key_uidx
  on public.message_log (event_key);

create index if not exists message_log_queue_idx
  on public.message_log (status, next_attempt_at, created_at);

alter table public.message_log enable row level security;

-- Atomically claim due messages. SKIP LOCKED prevents two cron requests from
-- processing the same row at the same time. Expired processing leases are
-- recoverable after a worker stops unexpectedly.
create or replace function public.claim_whatsapp_messages(
  p_limit integer default 10,
  p_max_attempts integer default 5,
  p_lock_seconds integer default 120
)
returns setof public.message_log
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with candidates as (
    select id
    from public.message_log
    where attempt_count < greatest(1, p_max_attempts)
      and next_attempt_at <= now()
      and (
        status in ('queued', 'failed')
        or (status = 'processing' and locked_until < now())
      )
    order by created_at asc
    for update skip locked
    limit least(greatest(1, p_limit), 50)
  )
  update public.message_log as messages
  set status = 'processing',
      attempt_count = messages.attempt_count + 1,
      locked_until = now() + make_interval(secs => greatest(30, p_lock_seconds)),
      updated_at = now()
  from candidates
  where messages.id = candidates.id
  returning messages.*;
end;
$$;

revoke all on function public.claim_whatsapp_messages(integer, integer, integer) from public;
grant execute on function public.claim_whatsapp_messages(integer, integer, integer) to service_role;
