-- ============================================================================
-- BetIndia — full schema for a FRESH Supabase project (migration).
-- Paste this whole file into the new project's SQL editor and Run once.
-- Order matters (user_activity view depends on users + transactions).
-- ============================================================================

-- 1. TRANSACTIONS (deposit/withdrawal webhooks) --------------------------------
create table if not exists public.transactions (
  id              bigint generated always as identity primary key,
  type            text not null check (type in ('deposit', 'withdrawal')),
  transaction_id  text,
  branch_id       text,
  user_id         text,
  user_name       text,
  mobile_number   text,
  amount          numeric,
  payment_status  text,
  utr_number      text,
  account_number  text,
  holder_name     text,
  ifsc_code       text,
  image           text,
  remarks         text,
  raw             jsonb not null default '{}'::jsonb,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index if not exists transactions_type_idx    on public.transactions (type);
create index if not exists transactions_status_idx  on public.transactions (payment_status);
create index if not exists transactions_created_idx on public.transactions (created_at desc);
create unique index if not exists transactions_uidx on public.transactions (type, transaction_id, branch_id);
alter table public.transactions enable row level security;

-- 2. WEBHOOK LOGS --------------------------------------------------------------
create table if not exists public.webhook_logs (
  id            bigint generated always as identity primary key,
  source        text,
  method        text,
  content_type  text,
  token_ok      boolean,
  status        int,
  ip            text,
  raw           jsonb,
  created_at    timestamptz not null default now()
);
create index if not exists webhook_logs_created_idx on public.webhook_logs (created_at desc);
alter table public.webhook_logs enable row level security;

-- 3. ANALYTICS EVENTS (SDK) ----------------------------------------------------
create table if not exists public.analytics_events (
  id          bigint generated always as identity primary key,
  event_name  text,
  created_at  timestamptz not null default now(),
  device_id   text,
  session_id  text,
  properties  jsonb not null default '{}'::jsonb,
  context     jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now()
);
create index if not exists analytics_events_event_name_idx on public.analytics_events (event_name);
create index if not exists analytics_events_session_idx    on public.analytics_events (session_id);
create index if not exists analytics_events_device_idx     on public.analytics_events (device_id);
create index if not exists analytics_events_created_at_idx on public.analytics_events (created_at desc);
alter table public.analytics_events enable row level security;
drop policy if exists "sdk anon insert" on public.analytics_events;
create policy "sdk anon insert" on public.analytics_events for insert to anon with check (true);

-- 4. APP SETTINGS (dashboard toggles) ------------------------------------------
create table if not exists public.app_settings (
  key        text primary key,
  value      text not null,
  updated_at timestamptz not null default now()
);
alter table public.app_settings enable row level security;
insert into public.app_settings (key, value) values
  ('automation_enabled', 'true'),
  ('automation_deposit', 'true'),
  ('automation_withdrawal', 'true'),
  ('winback_enabled', 'true'),
  ('statement_enabled', 'true')
on conflict (key) do nothing;

-- 5. MESSAGE LOG (durable WhatsApp queue + delivery log) -----------------------
create table if not exists public.message_log (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  channel text not null default 'whatsapp',
  template text not null,
  event_type text not null,
  transaction_id text,
  transaction_status text,
  mobile text not null,
  user_id text,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'queued'
    check (status in ('queued', 'processing', 'sent', 'failed', 'skipped')),
  detail text,
  provider_message_id text,
  attempt_count integer not null default 0,
  next_attempt_at timestamptz not null default now(),
  locked_until timestamptz,
  last_error text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists message_log_event_key_uidx on public.message_log (event_key);
create index if not exists message_log_queue_idx on public.message_log (status, next_attempt_at, created_at);
create index if not exists message_log_created_idx on public.message_log (created_at desc);
alter table public.message_log enable row level security;

create or replace function public.claim_whatsapp_messages(
  p_limit integer default 10,
  p_max_attempts integer default 5,
  p_lock_seconds integer default 120
)
returns setof public.message_log
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with candidates as (
    select id from public.message_log
    where attempt_count < greatest(1, p_max_attempts)
      and next_attempt_at <= now()
      and (status in ('queued', 'failed') or (status = 'processing' and locked_until < now()))
    order by created_at asc
    for update skip locked
    limit least(greatest(1, p_limit), 50)
  )
  update public.message_log as messages
  set status = 'processing',
      attempt_count = messages.attempt_count + 1,
      locked_until = now() + make_interval(secs => greatest(30, p_lock_seconds)),
      updated_at = now()
  from candidates
  where messages.id = candidates.id
  returning messages.*;
end;
$$;
revoke all on function public.claim_whatsapp_messages(integer, integer, integer) from public;
grant execute on function public.claim_whatsapp_messages(integer, integer, integer) to service_role;

-- 6. USERS (master list from the uploaded file) --------------------------------
create table if not exists public.users (
  user_id       text primary key,
  branch_id     text,
  mobile        text,
  name          text,
  language      text,
  register_date timestamptz,
  raw           jsonb,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index if not exists users_register_date_idx on public.users (register_date);
create index if not exists users_mobile_idx on public.users (mobile);
alter table public.users enable row level security;

-- 7. PLAYER ACTIVITY (RFM rollup) ----------------------------------------------
create table if not exists public.player_activity (
  user_id           text primary key,
  mobile            text,
  user_name         text,
  last_bet_at       timestamptz,
  last_txn_at       timestamptz,
  last_seen_at      timestamptz,
  last_active_at    timestamptz,
  deposits_90d      integer not null default 0,
  deposit_total_90d numeric not null default 0,
  r_score           integer,
  f_score           integer,
  m_score           integer,
  tier              text,
  refreshed_at      timestamptz,
  updated_at        timestamptz not null default now()
);
create index if not exists player_activity_last_active_idx on public.player_activity (last_active_at);
alter table public.player_activity enable row level security;

-- 8. USER ACTIVITY VIEW (users joined with transaction activity) ---------------
create or replace view public.user_activity as
select
  u.user_id, u.branch_id, u.mobile, u.name, u.language, u.register_date,
  t.last_txn_at,
  coalesce(t.deposits_count, 0) as deposits_count
from public.users u
left join (
  select user_id, max(created_at) as last_txn_at,
         count(*) filter (where type = 'deposit') as deposits_count
  from public.transactions
  group by user_id
) t on t.user_id = u.user_id;
